-- ============================================================
-- DEPRECATED — DO NOT USE
-- ============================================================
-- This migration previously DISABLED RLS on all tables.
-- It has been superseded by: 20260329000001_enforce_rls_production.sql
-- which ENABLES RLS with proper per-user policies.
--
-- SECURITY RULE: NEVER disable RLS in production.
-- See: C:\Users\asaid\.claude\JL-PROJECT-STANDARDS.md
-- ============================================================
-- (intentionally empty — all operations moved to 20260329000001)
